name: Clone Repo via SSH

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            set -e

            echo "🚀 Clonando repositorio..."

            # Clonar repo privado usando token
            git clone https://${{ secrets.TOKEN_DEPLOY_BOOKING }}@github.com/AlexMayhua/BookingIncaTrail.git /root/projects/BookingIncaTRail

            echo "✅ Repo clonado correctamente"